version: '3.7'

services:

  mysql5740:
    image: mysql:5.7.40
    container_name: mysql40
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3340:3306
    environment:
      # DONT DO THIS
      MYSQL_ROOT_PASSWORD: password

  mysql8036:
    image: mysql:8.0.36-debian
    container_name: mysql8036
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    ports:
      - 3340:3306
    environment:
      # DONT DO THIS
      MYSQL_ROOT_PASSWORD: password

